# Generated by Django 4.1.7 on 2023-03-09 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('idcart', models.IntegerField(db_column='idcart', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idcategory', models.IntegerField(db_column='idcategory', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('idcountries', models.IntegerField(db_column='idcountries', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('ccode', models.CharField(db_column='ccode', max_length=2, unique=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idproduct', models.IntegerField(db_column='idproduct', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=45)),
                ('description', models.CharField(db_column='description', max_length=255)),
                ('price', models.FloatField(db_column='price')),
                ('category', models.ForeignKey(db_column='category_idcategory', on_delete=django.db.models.deletion.CASCADE, to='models.category')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('idstate', models.IntegerField(db_column='idstate', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255, unique=True)),
                ('country', models.ForeignKey(db_column='countries_idcountries', on_delete=django.db.models.deletion.CASCADE, to='models.countries')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('idproduct_image', models.IntegerField(db_column='idproduct_image', primary_key=True, serialize=False)),
                ('image', models.CharField(db_column='image', max_length=255)),
                ('product', models.ForeignKey(db_column='product_idproduct', on_delete=django.db.models.deletion.CASCADE, to='models.product')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('contrasenia', models.CharField(max_length=45)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('country', models.ForeignKey(default=1010, on_delete=django.db.models.deletion.CASCADE, to='models.countries')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_users', to='auth.group', verbose_name='groups')),
                ('state', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.state')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_users_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('idcart_product', models.IntegerField(db_column='idcart_product', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='quantity')),
                ('cart', models.ForeignKey(db_column='cart_idcart', on_delete=django.db.models.deletion.CASCADE, to='models.cart')),
                ('product', models.ForeignKey(db_column='product_idproduct', on_delete=django.db.models.deletion.CASCADE, to='models.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(db_column='users_idusers', on_delete=django.db.models.deletion.CASCADE, to='models.customuser'),
        ),
    ]
