# Generated by Django 4.1.7 on 2023-03-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_purchase_purchaseproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('idpayments', models.AutoField(db_column='idpayments', primary_key=True, serialize=False)),
                ('purchase', models.IntegerField(db_column='purchase_idpurchase')),
                ('date', models.DateTimeField(db_column='date')),
                ('amount', models.FloatField(db_column='amount')),
                ('status', models.CharField(db_column='status', max_length=45)),
            ],
        ),
    ]
